------------------------- MODULE TwoBackers -------------------------
(* DELIBERATELY BROKEN VARIANT of ../PrefundedMiningPower.tla, generated by   *)
(* a textual patch; identical except for the lines marked MUTATION.          *)
(* assign drops the WalletAlreadyBacked check: a second depositor may add stake to a backed wallet. *)
(***************************************************************************)
(* TLA+ model of HunterMiningCore + PrefundedMiningPower (Linear VLT-65,   *)
(* slice S10b). It models the RULES of the build spec (SPEC.md: Hooks,     *)
(* Stake ledger, OWNER DECISION 2026-09-25 "SINGLE BUCKET", Release,       *)
(* Failsafe) and the core wiring rules of HunterMiningCore.sol.            *)
(*                                                                         *)
(* One TLA+ step = one successful Ethereum transaction. A transaction that *)
(* reverts is a stuttering step: its guard is simply false, so it changes  *)
(* nothing (this is how "rejected and nothing changes" is modelled).       *)
(*                                                                         *)
(* Abstractions (see README.md for the full list and why):                 *)
(*  - amounts are small naturals (MinStake=2, Lock=1, MaxDeposit=3);       *)
(*  - the wall-clock EXIT_COOLDOWN is abstracted to "always elapsed":      *)
(*    unassign is never blocked by time. Every cooldown-respecting         *)
(*    behaviour is a behaviour of this model, so safety results carry over;*)
(*  - PoW, digests, targets, tiers, baskets and the bonus curve value are  *)
(*    abstracted: any miner may win an ACTIVE challenge (nondeterminism);  *)
(*  - challenge ids are real naturals; the VIEW (ViewMap) canonicalises    *)
(*    them relative to latestChallengeId so the state graph is finite     *)
(*    (every comparison the contract makes is "== latest" / "< latest").   *)
(*  - Depositors and Wallets are disjoint, so the SelfAssignment rule is   *)
(*    vacuous here (it is covered by testSelfAssignmentRule).              *)
(*  - The old MiningPowerCustody ("Old") is abstract: it never gates, and  *)
(*    only its RetainedAssignments rule is kept (oldRetained).             *)
(***************************************************************************)
EXTENDS Naturals, FiniteSets, TLC

CONSTANTS
    Depositors,     \* stakers (backers)
    Wallets,        \* mining wallets (disjoint from Depositors)
    Buyer,          \* a non-mining NFT holder (secondary sale / loan / hunt)
    NoD, NoW,       \* "address(0)" for depositors / wallets
    MinStake,       \* E  (MIN_STAKE)
    Lock,           \* L  (LOCK_PER_MINT)
    MaxDeposit,     \* model bound: unassigned+assigned per depositor
    MaxTokens,      \* MAX_NFTS_EVER (mint-out)
    MaxChallenges,  \* bound on refreshExpiredSeed ids (liveness runs only)
    CurveEnabled,   \* CURVE_UNIT != 0: frozen stake also drives the bonus
    CutoverMode,    \* "batched" (Safe multiSend) or "twoTx" (two separate txs)
    S8Rules         \* FALSE: SPEC.md rules only. TRUE: + S8 decisions now in the
                    \* contract: first assign >= MIN_STAKE (decision 8), no new
                    \* backer while a removal still counts (decision 9,
                    \* WalletHasCountingRemoval), evictBacker, and deposit
                    \* refused once retired / failsafe fired
    , CoreChurn     \* TRUE: old custody, stop sunset and late attach are modelled.
                    \* FALSE (ledger runs): power in {None, New} only and no
                    \* sunset. The module cannot tell Old from None and the
                    \* sunset only removes behaviours, so FALSE over-approximates
                    \* every module-visible behaviour of TRUE.

ASSUME /\ Lock > 0 /\ MinStake >= Lock          \* constructor: minStake_ >= lockPerMint_
       /\ MaxDeposit >= MinStake /\ MaxTokens >= 1
       /\ Depositors \cap Wallets = {}
       /\ CutoverMode \in {"batched", "twoTx"}
       /\ CurveEnabled \in BOOLEAN /\ S8Rules \in BOOLEAN /\ CoreChurn \in BOOLEAN

Tokens   == 1..MaxTokens
Holders  == Wallets \cup {Buyer}
Powers   == {"None", "Old", "New"}
Amounts  == 0..MaxDeposit
Min(a, b) == IF a < b THEN a ELSE b

RECURSIVE SumSet(_, _)
SumSet(f, S) == IF S = {} THEN 0
                ELSE LET x == CHOOSE x \in S : TRUE IN f[x] + SumSet(f, S \ {x})

VARIABLES
    \* ---- HunterMiningCore ----
    cstate,        \* "Waiting" | "Active" | "Expired" (block-derived part of challengeState)
    stopped,       \* miningStopped (STOPPED)
    minted,        \* nftsMintedEver (ENDED when = MaxTokens)
    active,        \* activeChallengeId
    power,         \* miningPower: "None" | "Old" | "New"
    sunset,        \* block.timestamp > MINING_STOP_SUNSET (flips once)
    everAttached,  \* miningPowerWasAttached
    oldRetained,   \* old custody still holds assignments (its RetainedAssignments)
    \* ---- PrefundedMiningPower ----
    wired, retired, gateDisabled, latest, holdWaived,
    unassigned, assignedOf, assignedBy, assignee, backer,
    pendingOf, pendingEpoch, pendingBy, pendingEpochBy,
    removing, heldBy, heldEpochBy,
    frozenEpoch, frozenVal,        \* _frozen/_frozenStake (last freeze per wallet)
    totalStake, totalAssigned, totalCommitted,
    balance,                       \* HUNTER.balanceOf(module)
    lock,                          \* _committed[tokenId]
    \* ---- HunterNFT / HunterLifecycle ----
    owner,                         \* "none" | holder | "burned"
    beneficiary,                   \* finalBeneficiary (set by burn)
    \* ---- history / ghost variables (never read by the protocol) ----
    netIn,                         \* sum deposited - sum withdrawn
    gated,                         \* gated[t]: minted while New wired and gate enabled
    lockWrites, releaseCount, releasedTo,
    remBy, remEpoch,               \* matured stake d unassigned from w in epoch remEpoch[d]
    inGap, gapAllWaiting, gapSubmit, ungatedCutover, ungatedCutoverInWaiting,
    baseEpoch, baseline, rewiredSame

coreVars   == <<cstate, stopped, minted, active, power, sunset, everAttached, oldRetained>>
modVars    == <<wired, retired, gateDisabled, latest, holdWaived>>
ledgerVars == <<unassigned, assignedOf, assignedBy, assignee, backer,
                pendingOf, pendingEpoch, pendingBy, pendingEpochBy,
                removing, heldBy, heldEpochBy>>
freezeVars == <<frozenEpoch, frozenVal>>
bookVars   == <<totalStake, totalAssigned, totalCommitted, balance, lock>>
nftVars    == <<owner, beneficiary>>
ghostVars  == <<netIn, gated, lockWrites, releaseCount, releasedTo, remBy, remEpoch>>
gapVars    == <<inGap, gapAllWaiting, gapSubmit, ungatedCutover, ungatedCutoverInWaiting>>
baseVars   == <<baseEpoch, baseline, rewiredSame>>
vars == <<coreVars, modVars, ledgerVars, freezeVars, bookVars, nftVars, ghostVars, gapVars, baseVars>>

NoLock == [amount |-> 0, miner |-> NoW, backer |-> NoD, released |-> FALSE, fromMatured |-> TRUE]

-----------------------------------------------------------------------------
(* Derived views of contract state                                          *)

Ended      == minted >= MaxTokens
CoreState  == IF stopped THEN "Stopped" ELSE IF Ended THEN "Ended" ELSE cstate
\* _challengeOpen[active]: the module opened exactly the ids it snapshotted; the
\* core's id only grows and the module's latest equals the core's id at every
\* snapshot, so the active id is open iff it equals latest (and latest > 0).
OpenActive == latest # 0 /\ active = latest

PendOfCur(w) == IF pendingEpoch[w] = latest THEN pendingOf[w] ELSE 0
RemCur(w)    == IF pendingEpoch[w] = latest THEN removing[w] ELSE 0
PendByCur(d) == IF pendingEpochBy[d] = latest THEN pendingBy[d] ELSE 0

\* _maturedStake(latest, w)
Matured(w) ==
    IF pendingEpoch[w] = latest
    THEN assignedOf[w] - pendingOf[w] + (IF latest # holdWaived THEN removing[w] ELSE 0)
    ELSE assignedOf[w]

\* what the gate freezes / has frozen for the core's active challenge (_freeze)
GateValue(w) == IF frozenEpoch[w] = active THEN frozenVal[w] ELSE Matured(w)
\* _frozenPreview(w) for latestChallengeId (eligibilityOf / previewSubmit)
Preview(w)   == IF frozenEpoch[w] = latest THEN frozenVal[w] ELSE Matured(w)

\* live stake a lock can be paid from (_settleLock "available")
Live(w) == IF backer[w] = NoD THEN 0 ELSE Min(assignedOf[w], assignedBy[backer[w]])

\* heldStakeOf(d)
Held(d) == IF ~wired \/ retired \/ gateDisabled \/ latest = holdWaived THEN 0
           ELSE IF heldEpochBy[d] = latest THEN heldBy[d] ELSE 0

\* eligibilityOf(w).eligible
EligibleView(w) == wired /\ ~retired /\ (gateDisabled \/ Preview(w) >= MinStake)

\* The frozen stake influences something only while the module is the live
\* one and either the gate enforces MIN_STAKE or the bonus curve is on.
Counting == wired /\ ~retired /\ (~gateDisabled \/ CurveEnabled)

\* ghost attribution of counted stake to depositors
RemCounted(d, w) ==
    IF remEpoch[d] = latest /\ pendingEpoch[w] = latest /\ latest # holdWaived
    THEN remBy[d][w] ELSE 0
CountedFrom(d) ==
    (IF assignee[d] # NoW THEN assignedBy[d] - PendByCur(d) ELSE 0)
    + SumSet([w \in Wallets |-> RemCounted(d, w)], Wallets)

-----------------------------------------------------------------------------
Init ==
    /\ cstate = "Waiting" /\ stopped = FALSE /\ minted = 0 /\ active = 1
    /\ power \in IF CoreChurn THEN {"None", "Old"} ELSE {"None"}  \* fresh core / old custody attached
    /\ sunset = FALSE
    /\ everAttached = (power # "None")
    /\ oldRetained = FALSE
    /\ wired = FALSE /\ retired = FALSE /\ gateDisabled = FALSE
    /\ latest = 0 /\ holdWaived = 0
    /\ unassigned = [d \in Depositors |-> 0]
    /\ assignedOf = [w \in Wallets |-> 0]
    /\ assignedBy = [d \in Depositors |-> 0]
    /\ assignee = [d \in Depositors |-> NoW]
    /\ backer = [w \in Wallets |-> NoD]
    /\ pendingOf = [w \in Wallets |-> 0] /\ pendingEpoch = [w \in Wallets |-> 0]
    /\ pendingBy = [d \in Depositors |-> 0] /\ pendingEpochBy = [d \in Depositors |-> 0]
    /\ removing = [w \in Wallets |-> 0]
    /\ heldBy = [d \in Depositors |-> 0] /\ heldEpochBy = [d \in Depositors |-> 0]
    /\ frozenEpoch = [w \in Wallets |-> 0] /\ frozenVal = [w \in Wallets |-> 0]
    /\ totalStake = 0 /\ totalAssigned = 0 /\ totalCommitted = 0 /\ balance = 0
    /\ lock = [t \in Tokens |-> NoLock]
    /\ owner = [t \in Tokens |-> "none"] /\ beneficiary = [t \in Tokens |-> "none"]
    /\ netIn = 0
    /\ gated = [t \in Tokens |-> FALSE]
    /\ lockWrites = [t \in Tokens |-> 0] /\ releaseCount = [t \in Tokens |-> 0]
    /\ releasedTo = [t \in Tokens |-> "none"]
    /\ remBy = [d \in Depositors |-> [w \in Wallets |-> 0]]
    /\ remEpoch = [d \in Depositors |-> 0]
    /\ inGap = FALSE /\ gapAllWaiting = FALSE /\ gapSubmit = FALSE
    /\ ungatedCutover = FALSE /\ ungatedCutoverInWaiting = FALSE
    /\ baseEpoch = 0 /\ baseline = [w \in Wallets |-> 0] /\ rewiredSame = FALSE

-----------------------------------------------------------------------------
(* Core: challenge clock                                                    *)

\* seed parent block reached and its blockhash readable
SeedReady ==
    /\ ~stopped /\ ~Ended /\ cstate = "Waiting"
    /\ cstate' = "Active"
    /\ gapAllWaiting' = (gapAllWaiting /\ ~inGap)
    /\ UNCHANGED <<stopped, minted, active, power, sunset, everAttached, oldRetained,
                   modVars, ledgerVars, freezeVars, bookVars, nftVars, ghostVars,
                   inGap, gapSubmit, ungatedCutover, ungatedCutoverInWaiting, baseVars>>

\* more than 256 parent blocks since the seed block
Expire ==
    /\ ~stopped /\ ~Ended /\ cstate = "Active"
    /\ cstate' = "Expired"
    /\ UNCHANGED <<stopped, minted, active, power, sunset, everAttached, oldRetained,
                   modVars, ledgerVars, freezeVars, bookVars, nftVars, ghostVars, gapVars, baseVars>>

\* refreshExpiredSeed: new id; the wired module snapshots it
Refresh ==
    /\ ~stopped /\ ~Ended /\ cstate = "Expired"
    /\ active < MaxChallenges
    /\ cstate' = "Waiting"
    /\ active' = active + 1
    /\ IF power = "New"
       THEN /\ latest' = active + 1           \* snapshotChallenge(new id): fresh id, wired
            /\ wired' = TRUE /\ retired' = FALSE
       ELSE UNCHANGED <<latest, wired, retired>>
    /\ UNCHANGED <<stopped, minted, power, sunset, everAttached, oldRetained,
                   gateDisabled, holdWaived, ledgerVars, freezeVars, bookVars, nftVars,
                   ghostVars, gapVars, baseVars>>

SunsetPass ==
    /\ CoreChurn
    /\ ~sunset /\ sunset' = TRUE
    /\ UNCHANGED <<cstate, stopped, minted, active, power, everAttached, oldRetained,
                   modVars, ledgerVars, freezeVars, bookVars, nftVars, ghostVars, gapVars, baseVars>>

-----------------------------------------------------------------------------
(* Core: submitProof(w) — gate, digest check, counters, onProofAccepted     *)
(* (settlement), snapshot(next) or retire at mint-out, NFT mint. Atomic.    *)
(* The transient note is implicit: settlement happens iff the gate admitted *)
(* with the requirement enabled, inside this one step.                      *)

SubmitNew(w) ==
    LET t       == minted + 1
        frz     == GateValue(w)
        enforce == ~gateDisabled
        b       == backer[w]
        wl      == assignedOf[w] - Lock
        bl      == assignedBy[b] - Lock
        ended   == t >= MaxTokens
    IN
    /\ power = "New"
    /\ OpenActive                           \* _freeze: ChallengeNotOpen / StaleChallengeId
    /\ enforce => frz >= MinStake           \* NotEligible(2)
    /\ enforce => Live(w) >= Lock           \* settlement: InsufficientFunds
    /\ enforce => lock[t].amount = 0        \* LockAlreadyExists
    /\ frozenEpoch' = [frozenEpoch EXCEPT ![w] = active]
    /\ frozenVal'   = [frozenVal EXCEPT ![w] = frz]
    /\ IF enforce
       THEN /\ assignedOf' = [assignedOf EXCEPT ![w] = wl]
            /\ assignedBy' = [assignedBy EXCEPT ![b] = bl]
            /\ totalAssigned' = totalAssigned - Lock
            /\ totalStake' = totalStake - Lock
            /\ totalCommitted' = totalCommitted + Lock
            /\ pendingOf' = [pendingOf EXCEPT ![w] = IF pendingOf[w] > wl THEN wl ELSE pendingOf[w]]
            /\ pendingBy' = [pendingBy EXCEPT ![b] = IF pendingBy[b] > bl THEN bl ELSE pendingBy[b]]
            /\ backer' = [backer EXCEPT ![w] = IF wl = 0 THEN NoD ELSE b]
            /\ assignee' = [assignee EXCEPT ![b] = IF bl = 0 THEN NoW ELSE assignee[b]]
            /\ lock' = [lock EXCEPT ![t] =
                          [amount |-> Lock, miner |-> w, backer |-> b, released |-> FALSE,
                           fromMatured |-> (assignedBy[b] - PendByCur(b) >= Lock)]]
            /\ lockWrites' = [lockWrites EXCEPT ![t] = @ + 1]
       ELSE UNCHANGED <<assignedOf, assignedBy, totalAssigned, totalStake, totalCommitted,
                        pendingOf, pendingBy, backer, assignee, lock, lockWrites>>
    /\ gated' = [gated EXCEPT ![t] = enforce]
    /\ IF ended
       THEN \* _retireMiningPower(true) -> onMiningPowerDetached(true)
            /\ wired' = FALSE /\ retired' = TRUE /\ holdWaived' = latest
            /\ UNCHANGED latest
       ELSE \* snapshotChallenge(active + 1)
            /\ latest' = active + 1 /\ wired' = TRUE /\ retired' = FALSE
            /\ UNCHANGED holdWaived
    /\ UNCHANGED <<gateDisabled, unassigned, pendingEpoch, pendingEpochBy, removing,
                   heldBy, heldEpochBy, balance, gapVars>>

SubmitUngated(w) ==
    /\ power \in {"None", "Old"}
    /\ gated' = [gated EXCEPT ![minted + 1] = FALSE]
    /\ gapSubmit' = (gapSubmit \/ (power = "None" /\ inGap))
    /\ UNCHANGED <<modVars, ledgerVars, freezeVars, bookVars, lockWrites,
                   inGap, gapAllWaiting, ungatedCutover, ungatedCutoverInWaiting>>

Submit(w) ==
    /\ ~stopped /\ ~Ended /\ cstate = "Active"
    /\ \/ SubmitNew(w)
       \/ SubmitUngated(w)
    /\ minted' = minted + 1
    /\ active' = IF minted + 1 >= MaxTokens THEN active ELSE active + 1
    /\ cstate' = "Waiting"
    /\ owner' = [owner EXCEPT ![minted + 1] = w]
    /\ UNCHANGED <<stopped, power, sunset, everAttached, oldRetained, beneficiary,
                   netIn, releaseCount, releasedTo, remBy, remEpoch, baseVars>>

-----------------------------------------------------------------------------
(* Core: setMiningPower / attachMiningPowerLate / stopMining                *)

CanSetPower == ~sunset /\ ~stopped /\ ~Ended

\* module hook onMiningPowerDetached(false) + ghost baseline for the rewire check
DetachNewEffects ==
    /\ wired' = FALSE /\ holdWaived' = latest
    /\ baseEpoch' = latest
    /\ baseline' = [w \in Wallets |-> Preview(w)]

\* setMiningPower(0) as its own transaction
DetachTx ==
    /\ CanSetPower /\ power # "None"
    /\ power' = "None"
    /\ IF power = "New"
       THEN DetachNewEffects /\ UNCHANGED rewiredSame
       ELSE UNCHANGED <<wired, holdWaived, baseVars>>
    /\ inGap' = TRUE
    /\ gapAllWaiting' = (cstate = "Waiting")
    /\ gapSubmit' = FALSE
    /\ UNCHANGED <<cstate, stopped, minted, active, sunset, everAttached, oldRetained,
                   retired, gateDisabled, latest, ledgerVars, freezeVars, bookVars, nftVars,
                   ghostVars, ungatedCutover, ungatedCutoverInWaiting>>

\* snapshotChallenge(active) on a module that is not wired
AttachNewGuard == totalAssigned = 0                     \* RetainedAssignments
AttachNewEffects ==
    /\ latest' = active                                 \* unchanged when OpenActive (rewire)
    /\ wired' = TRUE /\ retired' = FALSE
    /\ rewiredSame' = OpenActive

\* setMiningPower(x != 0) as its own transaction
AttachTx(x) ==
    /\ CanSetPower /\ power = "None" /\ x \in {"Old", "New"}
    /\ CutoverMode = "batched" => ~everAttached         \* batched procedure: no 2-tx re-attach
    /\ IF x = "New"
       THEN AttachNewGuard /\ AttachNewEffects /\ UNCHANGED oldRetained
       ELSE ~oldRetained /\ UNCHANGED <<latest, wired, retired, rewiredSame, oldRetained>>
    /\ power' = x
    /\ everAttached' = TRUE
    /\ inGap' = FALSE
    /\ ungatedCutover' = (ungatedCutover \/ (inGap /\ gapSubmit))
    /\ ungatedCutoverInWaiting' = (ungatedCutoverInWaiting \/ (inGap /\ gapSubmit /\ gapAllWaiting))
    /\ UNCHANGED <<cstate, stopped, minted, active, sunset, gateDisabled, holdWaived,
                   ledgerVars, freezeVars, bookVars, nftVars, ghostVars,
                   gapAllWaiting, gapSubmit, baseEpoch, baseline>>

\* setMiningPower(0); setMiningPower(x) in ONE transaction (multiSend batch).
\* If the attach reverts the whole batch reverts (guard false).
Cutover(x) ==
    /\ CutoverMode = "batched"
    /\ CanSetPower /\ power # "None" /\ x \in {"Old", "New"}
    /\ IF x = "New"
       THEN /\ AttachNewGuard
            /\ latest' = active
            /\ wired' = TRUE /\ retired' = FALSE
            /\ IF power = "New"
               THEN \* detach then re-attach New into the same open challenge
                    /\ holdWaived' = latest
                    /\ baseEpoch' = latest
                    /\ baseline' = [w \in Wallets |-> Preview(w)]
                    /\ rewiredSame' = TRUE
               ELSE /\ rewiredSame' = OpenActive
                    /\ UNCHANGED <<holdWaived, baseEpoch, baseline>>
            /\ UNCHANGED oldRetained
       ELSE /\ ~oldRetained
            /\ IF power = "New"
               THEN DetachNewEffects /\ UNCHANGED rewiredSame
               ELSE UNCHANGED <<wired, holdWaived, baseVars>>
            /\ UNCHANGED <<latest, retired, oldRetained>>
    /\ power' = x
    /\ everAttached' = TRUE
    /\ UNCHANGED <<cstate, stopped, minted, active, sunset, gateDisabled,
                   ledgerVars, freezeVars, bookVars, nftVars, ghostVars, gapVars>>

\* attachMiningPowerLate: one-time, sunset-independent, only a fresh OLD-type
\* custody (PrefundedMiningPower lacks curveUnit(), so it can never use this path)
LateAttachOld ==
    /\ CoreChurn
    /\ ~everAttached /\ ~stopped /\ ~Ended /\ power = "None" /\ ~oldRetained
    /\ power' = "Old" /\ everAttached' = TRUE
    /\ UNCHANGED <<cstate, stopped, minted, active, sunset, oldRetained,
                   modVars, ledgerVars, freezeVars, bookVars, nftVars, ghostVars, gapVars, baseVars>>

StopMining ==
    /\ CanSetPower
    /\ stopped' = TRUE
    /\ IF power = "New"       \* _retireMiningPower(true)
       THEN wired' = FALSE /\ retired' = TRUE /\ holdWaived' = latest
       ELSE UNCHANGED <<wired, retired, holdWaived>>
    /\ UNCHANGED <<cstate, minted, active, power, sunset, everAttached, oldRetained,
                   gateDisabled, latest, ledgerVars, freezeVars, bookVars, nftVars,
                   ghostVars, gapVars, baseVars>>

\* abstract old-custody users: assign while it is wired, all exit while it is not
OldUsers ==
    /\ CoreChurn
    /\ \/ power = "Old" /\ ~oldRetained /\ oldRetained' = TRUE
       \/ power # "Old" /\ oldRetained /\ oldRetained' = FALSE
    /\ UNCHANGED <<cstate, stopped, minted, active, power, sunset, everAttached,
                   modVars, ledgerVars, freezeVars, bookVars, nftVars, ghostVars, gapVars, baseVars>>

-----------------------------------------------------------------------------
(* Module: stake ledger                                                     *)

Deposit(d, a) ==
    /\ a \in 1..MaxDeposit
    /\ S8Rules => ~retired /\ ~gateDisabled                 \* S8: Retired / GateDisabled
    /\ unassigned[d] + assignedBy[d] + a <= MaxDeposit       \* model bound only
    /\ unassigned' = [unassigned EXCEPT ![d] = @ + a]
    /\ totalStake' = totalStake + a
    /\ balance' = balance + a
    /\ netIn' = netIn + a
    /\ UNCHANGED <<coreVars, modVars, assignedOf, assignedBy, assignee, backer,
                   pendingOf, pendingEpoch, pendingBy, pendingEpochBy, removing, heldBy, heldEpochBy,
                   freezeVars, totalAssigned, totalCommitted, lock, nftVars,
                   gated, lockWrites, releaseCount, releasedTo, remBy, remEpoch, gapVars, baseVars>>

Assign(d, w, a) ==
    LET stale   == pendingEpoch[w] < latest
        pOf     == IF stale THEN 0 ELSE pendingOf[w]
        rem     == IF stale THEN 0 ELSE removing[w]
        pBy     == IF pendingEpochBy[d] < latest THEN 0 ELSE pendingBy[d]
        hBy     == IF heldEpochBy[d] < latest THEN 0 ELSE heldBy[d]
    IN
    /\ ~retired /\ wired /\ ~gateDisabled                    \* Retired / NotWired / GateDisabled
    /\ a \in 1..unassigned[d]                                \* InsufficientUnassigned
    /\ assignee[d] \in {NoW, w}                              \* MustUnassignFirst
    \* MUTATION: WalletAlreadyBacked check removed
    /\ (S8Rules /\ assignedOf[w] = 0) =>                     \* taking an empty slot (S8)
          /\ a >= MinStake                                   \* FirstAssignBelowMinimum
          /\ ~(pendingEpoch[w] = latest /\ removing[w] # 0    \* WalletHasCountingRemoval
               /\ latest # holdWaived)
    /\ unassigned' = [unassigned EXCEPT ![d] = @ - a]
    /\ assignedOf' = [assignedOf EXCEPT ![w] = @ + a]
    /\ assignedBy' = [assignedBy EXCEPT ![d] = @ + a]
    /\ totalAssigned' = totalAssigned + a
    /\ pendingOf' = [pendingOf EXCEPT ![w] = pOf + a]
    /\ removing' = [removing EXCEPT ![w] = rem]
    /\ pendingEpoch' = [pendingEpoch EXCEPT ![w] = latest]
    /\ pendingBy' = [pendingBy EXCEPT ![d] = pBy + a]
    /\ pendingEpochBy' = [pendingEpochBy EXCEPT ![d] = latest]
    /\ heldBy' = [heldBy EXCEPT ![d] = hBy]
    /\ heldEpochBy' = [heldEpochBy EXCEPT ![d] = latest]
    /\ assignee' = [assignee EXCEPT ![d] = w]
    /\ backer' = [backer EXCEPT ![w] = d]
    /\ UNCHANGED <<coreVars, modVars, freezeVars, totalStake, totalCommitted, balance, lock,
                   nftVars, ghostVars, gapVars, baseVars>>

\* _unassignFrom(d, w, a): shared by unassign and evictBacker
UnassignFrom(d, w, a) ==
    LET stale   == pendingEpoch[w] < latest
        pOf     == IF stale THEN 0 ELSE pendingOf[w]
        rem     == IF stale THEN 0 ELSE removing[w]
        pBy     == IF pendingEpochBy[d] < latest THEN 0 ELSE pendingBy[d]
        hBy     == IF heldEpochBy[d] < latest THEN 0 ELSE heldBy[d]
        pp      == Min(pBy, a)
        m       == a - pp                                   \* matured part
        rb      == IF remEpoch[d] < latest THEN [x \in Wallets |-> 0] ELSE remBy[d]
    IN
    /\ pendingBy' = [pendingBy EXCEPT ![d] = pBy - pp]
    /\ pendingOf' = [pendingOf EXCEPT ![w] = pOf - pp]
    /\ removing' = [removing EXCEPT ![w] = rem + m]
    /\ heldBy' = [heldBy EXCEPT ![d] = hBy + m]
    /\ pendingEpoch' = [pendingEpoch EXCEPT ![w] = latest]
    /\ pendingEpochBy' = [pendingEpochBy EXCEPT ![d] = latest]
    /\ heldEpochBy' = [heldEpochBy EXCEPT ![d] = latest]
    /\ assignedBy' = [assignedBy EXCEPT ![d] = @ - a]
    /\ assignedOf' = [assignedOf EXCEPT ![w] = @ - a]
    /\ totalAssigned' = totalAssigned - a
    /\ unassigned' = [unassigned EXCEPT ![d] = @ + a]
    /\ assignee' = [assignee EXCEPT ![d] = IF assignedBy[d] - a = 0 THEN NoW ELSE w]
    /\ backer' = [backer EXCEPT ![w] = IF assignedOf[w] - a = 0 THEN NoD ELSE backer[w]]
    /\ remBy' = [remBy EXCEPT ![d] = [rb EXCEPT ![w] = @ + m]]
    /\ remEpoch' = [remEpoch EXCEPT ![d] = latest]
    /\ UNCHANGED <<coreVars, modVars, freezeVars, totalStake, totalCommitted, balance, lock,
                   nftVars, netIn, gated, lockWrites, releaseCount, releasedTo, gapVars, baseVars>>

\* unassign: cooldown abstracted as always elapsed (see header)
Unassign(d, w, a) ==
    /\ assignee[d] = w                                       \* WrongAssignee
    /\ a \in 1..assignedBy[d]                                \* InsufficientAssigned
    /\ UnassignFrom(d, w, a)

\* evictBacker (S8): the mining wallet removes a backer whose stake on it is
\* below MIN_STAKE; unassign bookkeeping for the whole assignment, no cooldown
EvictBacker(w) ==
    /\ S8Rules
    /\ 0 < assignedOf[w] /\ assignedOf[w] < MinStake          \* BackerNotEvictable
    /\ UnassignFrom(backer[w], w, assignedOf[w])

Withdraw(d, a) ==
    /\ a \in 1..(unassigned[d] - Min(Held(d), unassigned[d]))   \* StakeHeldUntilNextChallenge
    /\ unassigned' = [unassigned EXCEPT ![d] = @ - a]
    /\ totalStake' = totalStake - a
    /\ balance' = balance - a
    /\ netIn' = netIn - a
    /\ UNCHANGED <<coreVars, modVars, assignedOf, assignedBy, assignee, backer,
                   pendingOf, pendingEpoch, pendingBy, pendingEpochBy, removing, heldBy, heldEpochBy,
                   freezeVars, totalAssigned, totalCommitted, lock, nftVars,
                   gated, lockWrites, releaseCount, releasedTo, remBy, remEpoch, gapVars, baseVars>>

\* failsafe guardian, one-way
DisableRequirement ==
    /\ ~gateDisabled /\ gateDisabled' = TRUE
    /\ UNCHANGED <<coreVars, wired, retired, latest, holdWaived, ledgerVars, freezeVars,
                   bookVars, nftVars, ghostVars, gapVars, baseVars>>

-----------------------------------------------------------------------------
(* NFT: transfer (sale / loan default / hunt), burn, claim                   *)

\* Transfer (sale / loan default / hunt) followed by redeemAndDestroy by the
\* then-current owner h, folded into one step: the intermediate "held by h"
\* state touches neither the module nor the core, so folding it only removes
\* interleavings that cannot change any module variable. h = the miner means
\* "never transferred". The lifecycle records finalBeneficiary = h.
Burn(t, h) ==
    /\ owner[t] \in Wallets
    /\ h \in {owner[t], Buyer}
    /\ owner' = [owner EXCEPT ![t] = "burned"]
    /\ beneficiary' = [beneficiary EXCEPT ![t] = h]
    /\ UNCHANGED <<coreVars, modVars, ledgerVars, freezeVars, bookVars,
                   ghostVars, gapVars, baseVars>>

\* claimCommitted by caller c
Claim(t, c) ==
    /\ lock[t].amount > 0                     \* NoLock
    /\ ~lock[t].released                      \* AlreadyReleased
    /\ owner[t] = "burned"                    \* TokenNotBurned
    /\ c = beneficiary[t]                     \* NotBeneficiary
    /\ lock' = [lock EXCEPT ![t].released = TRUE]
    /\ totalCommitted' = totalCommitted - lock[t].amount
    /\ balance' = balance - lock[t].amount
    /\ releaseCount' = [releaseCount EXCEPT ![t] = @ + 1]
    /\ releasedTo' = [releasedTo EXCEPT ![t] = c]
    /\ UNCHANGED <<coreVars, modVars, ledgerVars, freezeVars, totalStake, totalAssigned,
                   nftVars, netIn, gated, lockWrites, remBy, remEpoch, gapVars, baseVars>>

-----------------------------------------------------------------------------
Next ==
    \/ SeedReady \/ Expire \/ Refresh \/ SunsetPass
    \/ \E w \in Wallets : Submit(w)
    \/ DetachTx
    \/ \E x \in IF CoreChurn THEN {"Old", "New"} ELSE {"New"} : AttachTx(x) \/ Cutover(x)
    \/ LateAttachOld \/ StopMining \/ OldUsers \/ DisableRequirement
    \/ \E w \in Wallets : EvictBacker(w)
    \/ \E d \in Depositors, a \in 1..MaxDeposit :
          Deposit(d, a) \/ Withdraw(d, a) \/ \E w \in Wallets : Assign(d, w, a) \/ Unassign(d, w, a)
    \/ \E t \in Tokens : \E h \in Holders : Burn(t, h) \/ Claim(t, h)

Spec == Init /\ [][Next]_vars

\* exits used by the liveness run
UnassignAll(d) == assignee[d] # NoW /\ Unassign(d, assignee[d], assignedBy[d])
WithdrawAll(d) == unassigned[d] > 0 /\ Withdraw(d, unassigned[d])

LiveSpec == Spec
    /\ \A w \in Wallets : WF_vars(Submit(w))
    /\ \A d \in Depositors : WF_vars(UnassignAll(d)) /\ WF_vars(WithdrawAll(d))

-----------------------------------------------------------------------------
(* Invariants                                                               *)

TypeOK ==
    /\ cstate \in {"Waiting", "Active", "Expired"}
    /\ stopped \in BOOLEAN /\ sunset \in BOOLEAN /\ everAttached \in BOOLEAN
    /\ minted \in 0..MaxTokens /\ active \in Nat \ {0} /\ power \in Powers
    /\ wired \in BOOLEAN /\ retired \in BOOLEAN /\ gateDisabled \in BOOLEAN
    /\ latest \in Nat /\ latest <= active /\ holdWaived <= latest
    /\ unassigned \in [Depositors -> Amounts] /\ assignedBy \in [Depositors -> Amounts]
    \* per-wallet sums are typed Nat: bounding them would silently encode OneBackerPerWallet
    /\ assignedOf \in [Wallets -> Nat]
    /\ pendingOf \in [Wallets -> Nat] /\ removing \in [Wallets -> Nat]
    /\ pendingBy \in [Depositors -> Amounts] /\ heldBy \in [Depositors -> Nat]
    /\ assignee \in [Depositors -> Wallets \cup {NoW}] /\ backer \in [Wallets -> Depositors \cup {NoD}]
    /\ \A w \in Wallets : pendingEpoch[w] <= latest /\ frozenEpoch[w] <= active
    /\ \A d \in Depositors : pendingEpochBy[d] <= latest /\ heldEpochBy[d] <= latest
                             /\ remEpoch[d] <= latest
    /\ totalStake \in Nat /\ totalAssigned \in Nat /\ totalCommitted \in Nat /\ balance \in Nat
    /\ \A t \in Tokens : owner[t] \in Holders \cup {"none", "burned"}
    /\ \A w \in Wallets : PendOfCur(w) <= assignedOf[w]
    /\ \A d \in Depositors : PendByCur(d) <= assignedBy[d]

\* the module the core reads is wired and tracks the core's challenge id
WiredTracksCore ==
    /\ wired => power = "New"
    /\ (power = "New" /\ ~stopped /\ ~Ended) => (wired /\ ~retired /\ latest = active)

\* per-wallet buckets agree with per-depositor shares and the ghost attribution
LedgerConsistent ==
    /\ \A w \in Wallets :
          /\ backer[w] = NoD => PendOfCur(w) = 0
          /\ backer[w] # NoD => PendOfCur(w) = PendByCur(backer[w])
          /\ RemCur(w) = SumSet([d \in Depositors |->
                IF remEpoch[d] = latest THEN remBy[d][w] ELSE 0], Depositors)

\* Solvency: module balance = unassigned + assigned + unreleased locks
Unreleased(t) == IF lock[t].released THEN 0 ELSE lock[t].amount
Solvency ==
    /\ balance = SumSet(unassigned, Depositors) + SumSet(assignedOf, Wallets)
                 + SumSet([t \in Tokens |-> Unreleased(t)], Tokens)
    /\ totalStake = SumSet(unassigned, Depositors) + SumSet(assignedBy, Depositors)
    /\ totalAssigned = SumSet(assignedOf, Wallets)
    /\ totalAssigned = SumSet(assignedBy, Depositors)
    /\ totalCommitted = SumSet([t \in Tokens |-> Unreleased(t)], Tokens)
    /\ balance >= totalStake + totalCommitted

\* NoDoubleCount: sum over wallets of the frozen stake for the open challenge
\* (recorded, or what _freeze would record) <= deposited - withdrawn.
CountedSum == SumSet([w \in Wallets |-> Preview(w)], Wallets)
NoDoubleCount == Counting => CountedSum <= netIn
\* stronger: <= stake currently held as stake (excludes committed locks)
NoDoubleCountStrict == Counting => CountedSum <= totalStake

\* OneBackerPerWallet: assignedOf[w] > 0 => exactly one depositor backs w
OneBackerPerWallet ==
    \A w \in Wallets :
        assignedOf[w] > 0 =>
            /\ backer[w] \in Depositors
            /\ {d \in Depositors : assignee[d] = w /\ assignedBy[d] > 0} = {backer[w]}
            /\ assignedBy[backer[w]] = assignedOf[w]

\* StakeNeverLeavesWhileCounting: every unit of stake counted for the open
\* challenge (matured assigned stake + matured removals added back) is still
\* inside the module, attributed per depositor via the ghost remBy.
StakeNeverLeavesWhileCounting ==
    Counting => \A d \in Depositors : CountedFrom(d) <= unassigned[d] + assignedBy[d]

\* LockIffMint: lock for t exists <=> t minted while New wired with the gate enabled
LockIffMint ==
    \A t \in Tokens : (lock[t].amount > 0) <=> (t <= minted /\ gated[t])

OneLockPerToken == \A t \in Tokens : lockWrites[t] <= 1 /\ lock[t].amount \in {0, Lock}

ReleaseOnceAfterBurnToBeneficiary ==
    \A t \in Tokens :
        /\ releaseCount[t] <= 1
        /\ (releaseCount[t] = 1) <=> lock[t].released
        /\ lock[t].released => /\ owner[t] = "burned"
                               /\ beneficiary[t] \in Holders
                               /\ releasedTo[t] = beneficiary[t]

\* CutoverNoGap. batched: no ungated submitProof inside any cutover.
\* twoTx: an ungated submitProof inside a cutover gap is impossible when the
\* whole gap (detach tx .. attach tx) stays inside WAITING_FOR_SEED.
CutoverNoGap ==
    IF CutoverMode = "batched" THEN ~ungatedCutover ELSE ~ungatedCutoverInWaiting

\* RewireSameEpochLowersOnly: after detach -> attach into the same challenge,
\* no wallet's frozen (or to-be-frozen) value exceeds its value at the detach.
RewireSameEpochLowersOnly ==
    (rewiredSame /\ wired /\ latest = baseEpoch) =>
        \A w \in Wallets : Preview(w) <= baseline[w]

\* the only freeze that can exist for a still-open, counting challenge is none:
\* every accepted proof closes its challenge (supports the preview abstraction)
NoFreezeInOpenChallenge == Counting => \A w \in Wallets : frozenEpoch[w] # latest

\* EligibleWinnerNeverBlocked (state form): a wallet the view reports eligible
\* whose backer's live stake covers the lock can always submit successfully.
CanWin(w) ==
    /\ ~stopped /\ ~Ended /\ cstate = "Active" /\ power = "New"
    /\ EligibleView(w)
    /\ (~gateDisabled => Live(w) >= Lock)
EligibleWinnerNeverBlockedInv == \A w \in Wallets : CanWin(w) => ENABLED Submit(w)

\* ExitsAlwaysOpen (state form): after retirement or the failsafe every
\* depositor can unassign everything and withdraw everything, right now.
ExitsOpenInv ==
    (retired \/ gateDisabled) =>
        \A d \in Depositors :
            /\ assignee[d] # NoW => ENABLED UnassignAll(d)
            /\ unassigned[d] > 0 => ENABLED WithdrawAll(d)
            /\ Held(d) = 0

-----------------------------------------------------------------------------
(* Action properties (checked on every step)                                 *)

\* FrozenVsLive: a gated acceptance happens only when the frozen stake passes
\* AND the live stake covers the lock; otherwise the tx reverts: freezes and
\* locks change only together with a mint.
FrozenVsLive ==
    [][ /\ (minted' = minted + 1 /\ power = "New" /\ ~gateDisabled) =>
             LET t == minted + 1  w == owner'[t] IN
               /\ GateValue(w) >= MinStake /\ Live(w) >= Lock
               /\ lock'[t].amount = Lock /\ lock'[t].miner = w /\ lock'[t].backer = backer[w]
               /\ assignedOf'[w] = assignedOf[w] - Lock
        /\ (minted' = minted) =>
             /\ frozenEpoch' = frozenEpoch /\ frozenVal' = frozenVal
             /\ \A t \in Tokens : lock'[t].amount = lock[t].amount ]_vars

\* PostSunsetPermanent: once the sunset passed, whether New is wired never
\* changes, nothing can stop mining by key, and the only pointer change left
\* is the one-time late attach of a fresh old-type custody.
PostSunsetPermanent ==
    [][ sunset =>
          /\ (power' = "New") = (power = "New")
          /\ (stopped' = stopped)
          /\ (power' # power) => (power = "None" /\ power' = "Old" /\ ~everAttached) ]_vars

\* locks are never rewritten, releases never undone
LocksMonotone ==
    [][ \A t \in Tokens : /\ lock[t].amount > 0 => lock'[t].amount = lock[t].amount
                          /\ lock[t].released => lock'[t].released ]_vars

-----------------------------------------------------------------------------
(* Liveness                                                                  *)

EligibleWinnerNeverBlocked == \A w \in Wallets : []<>(~CanWin(w))
ExitsAlwaysOpen ==
    \A d \in Depositors :
        (retired \/ gateDisabled) ~> (unassigned[d] + assignedBy[d] = 0)

-----------------------------------------------------------------------------
(* Witnesses: EXPECTED to be violated (they prove the scenarios are reachable, *)
(* i.e. the invariants above are not vacuous).                                *)

WitnessAdmittedButShort ==
    ~(\E w \in Wallets : cstate = "Active" /\ ~stopped /\ ~Ended /\ power = "New"
                        /\ ~gateDisabled /\ GateValue(w) >= MinStake /\ Live(w) < Lock)
WitnessRewireSameEpoch == ~(rewiredSame /\ wired /\ latest = baseEpoch
                            /\ \E w \in Wallets : baseline[w] > 0)
WitnessClaimToBuyer == ~(\E t \in Tokens : lock[t].released /\ releasedTo[t] = Buyer)
WitnessUngatedCutover == ~ungatedCutover
\* design check (not in the issue list): a lock is paid from stake that
\* counted (was matured) for the challenge it settles
LockFromCountingStake == \A t \in Tokens : lock[t].amount > 0 => lock[t].fromMatured

-----------------------------------------------------------------------------
(* VIEW: canonical state. Stale epoch-tagged buckets read exactly as zeroed   *)
(* buckets, and ids are only ever compared for equality with latest/active,  *)
(* so this map is a bisimulation quotient (valid while MaxChallenges does    *)
(* not bind; the main cfg sets it out of reach).                             *)

Cur(e) == e = latest
ViewMap ==
    <<cstate, stopped, minted, active = latest, latest = 0, power, sunset, everAttached,
      oldRetained, wired, retired, gateDisabled, Cur(holdWaived),
      unassigned, assignedOf, assignedBy, assignee, backer,
      [w \in Wallets |-> <<PendOfCur(w), RemCur(w)>>],
      [d \in Depositors |-> <<PendByCur(d), IF Cur(heldEpochBy[d]) THEN heldBy[d] ELSE 0>>],
      [w \in Wallets |-> IF frozenEpoch[w] = active THEN frozenVal[w] + 1 ELSE 0],
      [w \in Wallets |-> IF frozenEpoch[w] = latest THEN frozenVal[w] + 1 ELSE 0],
      totalStake, totalAssigned, totalCommitted, balance,
      \* lock.miner / lock.backer are informational (read only by FrozenVsLive on
      \* the step that creates the lock), so they are projected out
      [t \in Tokens |-> <<lock[t].amount, lock[t].released, lock[t].fromMatured>>],
      \* NFT identities gate nothing except "Claim caller = beneficiary" (exactly
      \* one caller either way): keep live/burned, burned-by-non-miner, and
      \* whether the payout went to the beneficiary
      [t \in Tokens |-> <<IF owner[t] \in Wallets THEN "live" ELSE owner[t],
                          beneficiary[t] = Buyer, releasedTo[t] = beneficiary[t]>>],
      netIn, gated, lockWrites, releaseCount,
      [d \in Depositors |-> IF Cur(remEpoch[d]) THEN remBy[d] ELSE [w \in Wallets |-> 0]],
      inGap, IF inGap THEN <<gapAllWaiting, gapSubmit>> ELSE <<>>,
      ungatedCutover, ungatedCutoverInWaiting,
      \* baseline is read only while latest = baseEpoch (latest never decreases)
      IF Cur(baseEpoch) THEN <<baseline, rewiredSame>> ELSE <<>>>>
Symm == Permutations(Depositors) \cup Permutations(Wallets)
=============================================================================
